# Generated by Django 3.2.3 on 2021-05-28 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoafisica',
            name='nome_mae',
            field=models.CharField(default='', max_length=150, verbose_name='Nome da mãe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='nome_pai',
            field=models.CharField(max_length=150, null=True, verbose_name='Nome do pai'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='nome',
            field=models.CharField(max_length=150, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='sigla',
            field=models.CharField(max_length=15, verbose_name='Sigla'),
        ),
        migrations.CreateModel(
            name='RelacaoDependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentesco', models.PositiveSmallIntegerField(choices=[(1, 'Pai/Mãe'), (2, 'Avó/Avó'), (3, 'Tio/Tia'), (4, 'Primo/Prima'), (5, 'Outro')], verbose_name='Parentesco')),
                ('dependente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsaveis', to='base.pessoafisica', verbose_name='Dependente')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='_deps', to='base.pessoafisica', verbose_name='Responsável')),
            ],
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='dependentes',
            field=models.ManyToManyField(through='base.RelacaoDependencia', to='base.PessoaFisica'),
        ),
        migrations.AddConstraint(
            model_name='relacaodependencia',
            constraint=models.UniqueConstraint(fields=('responsavel', 'dependente'), name='relacao_resp_dep_uniq'),
        ),
    ]
