# Generated by Django 3.2 on 2021-05-04 12:42

from django.db import migrations, models
import localflavor.br.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210503_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoafisica',
            name='cpf',
            field=localflavor.br.models.BRCPFField(default='', max_length=14, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='estado_civil',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Solteiro'), (1, 'Casado'), (2, 'Viúvo'), (3, 'Divorciado'), (4, 'União estável')], null=True),
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='falecido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('I', 'Indefinido'), ('N', 'Não Informado')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='tipo_sanguineo',
            field=models.CharField(blank=True, choices=[('A+', 'A Positivo'), ('A-', 'A Negativo'), ('B+', 'B Positivo'), ('B-', 'B Negativo'), ('AB+', 'Ab Positivo'), ('AB-', 'Ab Negativo'), ('O+', 'O Positivo'), ('O-', 'O Negativo')], max_length=3, null=True),
        ),
    ]
