# Generated by Django 3.2 on 2021-05-04 17:46

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import iguana.base.models.telefone
import localflavor.br.models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_auto_20210504_1404"),
    ]

    operations = [
        migrations.CreateModel(
            name="PessoaJuridica",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="base.user",
                    ),
                ),
                ("cnpj", localflavor.br.models.BRCNPJField(max_length=18, unique=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("base.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="endereco",
            name="bairro",
            field=models.CharField(default="", max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="endereco",
            name="cep",
            field=localflavor.br.models.BRPostalCodeField(default="", max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="endereco",
            name="cidade",
            field=models.CharField(default="", max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="endereco",
            name="complemento",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="endereco",
            name="logradouro",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="endereco",
            name="numero",
            field=models.CharField(default="", max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="endereco",
            name="tipo",
            field=models.IntegerField(
                choices=[(1, "Comercial"), (2, "Residencial"), (3, "Rural")], default=2
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="endereco",
            name="uf",
            field=localflavor.br.models.BRStateField(default="", max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="telefone",
            name="numero",
            field=models.CharField(
                default="",
                max_length=120,
                validators=[iguana.base.models.telefone.TelefoneRegexValidator()],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="telefone",
            name="observacoes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="telefone",
            unique_together={("user", "numero")},
        ),
    ]
