# Generated by Django 3.2.3 on 2021-05-13 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_pessoafisica_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoIdentificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('RG', 'RG'), ('CTPS', 'Cateira de Trabalho - CTPS'), ('CNH', 'Carteira Nacional de Habilitação - CNH'), ('TITULO_ELEITOR', 'Título de Eleitor'), ('PASSAPORTE', 'Passaporte'), ('RESERV', 'Certificado de Reservista'), ('CERT_NASC', 'Certidão de Nascimento')], max_length=50, verbose_name='Tipo')),
                ('pessoa_fisica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.pessoafisica', verbose_name='Pessoa Física')),
            ],
        ),
        migrations.AddConstraint(
            model_name='documentoidentificacao',
            constraint=models.UniqueConstraint(fields=('pessoa_fisica_id', 'tipo'), name='unique_pessoa_fisica_id_tipo'),
        ),
    ]
